<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/18 20:09:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tesis',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
