<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/18 20:15:11
sfConfig::add(array(
  'mod_administrarequipos_enabled' => true,
  'mod_administrarequipos_view_class' => 'sfPHP',
));
