<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/18 20:12:19
sfConfig::add(array(
  'mod_administrarcategorias_enabled' => true,
  'mod_administrarcategorias_view_class' => 'sfPHP',
));
