<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/18 21:52:26
sfConfig::add(array(
  'mod_administrarempleados_enabled' => true,
  'mod_administrarempleados_view_class' => 'sfPHP',
));
