<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/18 21:45:36
sfConfig::add(array(
  'mod_administrarclientes_enabled' => true,
  'mod_administrarclientes_view_class' => 'sfPHP',
));
